name: Test, build, and publish the package

on:
  push:
    branches: [main]

jobs:
  test-build-and-publish:
    name: Test, build, and publish the package
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Check requirements.txt is up to date
        run: |
          source venv/bin/activate
          pip install .[all]
          pip uninstall -y service-oriented
          pip freeze > requirements.txt

          if ! `git diff --quiet`; then
            echo "pip freeze caused file changes, failing!"
            git diff
            exit 1
          fi

      - name: Check style
        run: |
          source venv/bin/activate
          make style

          if ! `git diff --quiet`; then
            echo "make style caused file changes, failing!"
            git diff
            exit 1
          fi

      - name: Run tests and build package
        run: |
          source venv/bin/activate
          coverage run -m pytest
          coverage report | tee .meta/coverage/report.txt
          coverage-badge -f -o .meta/coverage/badge.svg
          export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_SERVICE_ORIENTED="$(cat VERSION)"
          python -m build

      - name: Checkout tdg5/github-action-pack
        uses: actions/checkout@v4
        with:
          path: .github/actions/tdg5/github-action-pack
          ref: v0.0.5
          repository: tdg5/github-action-pack

      - name: Commit and push code coverage snapshot
        uses: ./.github/actions/tdg5/github-action-pack/packages/stage-files-and-commit-and-push-action/src
        with:
          authorEmail: dannyguinther+spamburglar@gmail.com
          authorName: Spamburglar
          commitMessage: "[skip actions] Update code coverage snapshot"
          optionalFilePaths: |
            .meta/coverage/badge.svg
            .meta/coverage/report.txt

      - name: Increment version
        uses: ./.github/actions/tdg5/github-action-pack/packages/increment-version-file-action/src
        with:
          authorEmail: dannyguinther+spamburglar@gmail.com
          authorName: Spamburglar
          commitMessage: "[skip actions] Increment version for next development cycle"
          versionFilePath: VERSION
          versionFormat: python

      - name: Publish package to pypi
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_USERNAME: __token__
        run: |
          source venv/bin/activate
          python -m twine upload dist/*

      # Add the tag after publishing the package so it is more likely that we
      # end up with a package without a tag than a tag without a package.
      - name: Create and push tag for published version
        run: |
          VERSION="$(git show HEAD~1:VERSION)"
          TAG_NAME="v${VERSION}"
          git tag "$TAG_NAME" HEAD~1
          git push origin "$TAG_NAME"
